name = "Bumper"
uuid = "8ce10254-0962-460f-a3d8-1f77fea1446e"
authors = ["MasonProtter <mason.protter@icloud.com>"]
version = "0.7.1"

[deps]
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"

[compat]
julia = "1.6"
UnsafeArrays = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
