name = "Bumper"
uuid = "8ce10254-0962-460f-a3d8-1f77fea1446e"
authors = ["MasonProtter <mason.protter@icloud.com>"]
version = "0.2.0"

[deps]
StrideArraysCore = "7792a7ef-975c-4747-a70f-980b88e8d1da"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
